Bump version to 5.15.2
rogii-com/qt5 pull request #12
Opened 2021-09-28 06:58 UTC by Shkarlatov

2021-10-01 11:56 UTC, mr-bit commented on CMakeLists.txt
> +if((NOT PYTHON_RESULT EQUAL 0) OR (NOT PYTHON_ALL_OUTPUT MATCHES "2\.7"))
Add support for python 3.6.x too and update message below

2021-10-01 12:05 UTC, mr-bit commented on rogii/build_common.cmake
> +if(WIN32)
Remove and use -G Ninja below

2021-10-01 12:07 UTC, mr-bit commented on rogii/version.cmake
> +SET(ROGII_QT_MAJOR_VERSION 5)
ROGII_MAJOR_VERSION, ROGII_MINOR_VERSION, ROGII_PATCH_VERSION and ROGII_PKG_VERSION for uniformity

2021-10-01 12:14 UTC, mr-bit requested changes
Small changes

2021-10-05 06:16 UTC, chak3r approved these changes

2021-10-05 13:14 UTC, mr-bit requested changes

2021-10-05 13:14 UTC, mr-bit commented on CMakeLists.txt
> +if((NOT PYTHON_RESULT EQUAL 0))
```
if((NOT PYTHON_RESULT EQUAL 0) OR ((NOT PYTHON_ALL_OUTPUT MATCHES "2\.7") AND (NOT PYTHON_ALL_OUTPUT MATCHES "3\.6")))
    message(
        FATAL_ERROR
        "Python 2.7.x or 3.6.x is not in the PATH."
    )
endif()
```

2021-10-05 13:36 UTC, mr-bit approved these changes

2021-10-05 13:36 UTC, merged